### ISSUE TITLE
Make release idempotent

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/publish-go-sdk-action#6]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

If the publish for the given version has already been done, don't error, but just print a warning that the publish was skipped.

This should be achived by checking for the existance of the git tag. We could still run the cache check step to ensure the SDK is available and fetchable.

**Comment by VenelinMartinov** [comment]
Hit this in https://github.com/pulumi/pulumi-aiven/actions/runs/9290726726/job/25605598745
